const PLAY_CARD_ENTRY_ANIMATION_MS = 400
const COMPLETED_TRICK_PREVIEW_MS = 220
const TRICK_COLLECTION_GATHER_MS = 180
const TRICK_COLLECTION_FLY_MS = 420
const TRICK_COLLECTION_CARD_STAGGER_MS = 35
const TRICK_COLLECTION_CARD_COUNT = 4

const PLAY_AFTER_TRICK_COLLECTION_DELAY_MS =
  PLAY_CARD_ENTRY_ANIMATION_MS +
  COMPLETED_TRICK_PREVIEW_MS +
  TRICK_COLLECTION_GATHER_MS +
  TRICK_COLLECTION_FLY_MS +
  TRICK_COLLECTION_CARD_STAGGER_MS * (TRICK_COLLECTION_CARD_COUNT - 1)

export const SERVER_TIMING_CONFIG = {
  cutHumanTimeoutMs: 15000,
  cutBotDelayMs: 800,

  bidHumanTimeoutMs: 15000,
  bidBotDelayMs: 800,

  playHumanTimeoutMs: 15000,
  playBotDelayMs: 800,
  playAfterTrickCollectionDelayMs: PLAY_AFTER_TRICK_COLLECTION_DELAY_MS,

  summaryVisibleMs: 5000,
} as const

export type ServerTimingConfig = typeof SERVER_TIMING_CONFIG
